# Generated by Django 4.2.7 on 2025-08-29 14:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(
                        upload_to="event_files/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["log", "txt", "csv"]
                            )
                        ],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("processed", models.BooleanField(default=False)),
                ("total_events", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="EventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_no", models.IntegerField()),
                ("version", models.IntegerField()),
                ("account_id", models.CharField(db_index=True, max_length=50)),
                ("instance_id", models.CharField(max_length=50)),
                ("src_addr", models.GenericIPAddressField(db_index=True)),
                ("dst_addr", models.GenericIPAddressField(db_index=True)),
                ("src_port", models.IntegerField()),
                ("dst_port", models.IntegerField()),
                ("protocol", models.IntegerField()),
                ("packets", models.BigIntegerField()),
                ("bytes_transferred", models.BigIntegerField()),
                ("start_time", models.BigIntegerField(db_index=True)),
                ("end_time", models.BigIntegerField(db_index=True)),
                ("action", models.CharField(db_index=True, max_length=20)),
                ("log_status", models.CharField(max_length=20)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="events.eventfile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["src_addr", "start_time"],
                        name="events_even_src_add_f2e37e_idx",
                    ),
                    models.Index(
                        fields=["dst_addr", "start_time"],
                        name="events_even_dst_add_6e4d55_idx",
                    ),
                    models.Index(
                        fields=["action", "start_time"],
                        name="events_even_action_45417a_idx",
                    ),
                    models.Index(
                        fields=["account_id", "start_time"],
                        name="events_even_account_f0456d_idx",
                    ),
                ],
            },
        ),
    ]
