version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - uploads_data:/app/uploads
    environment:
      - DEBUG=1
      - PYTHONUNBUFFERED=1

volumes:
  uploads_data: